name: studymate
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  # 状态管理
  get: ^4.6.6
  # 本地缓存
  shared_preferences: ^2.5.1
  # 路由管理
  go_router: ^14.7.2
  # 代码生成
  freezed: ^2.5.8
  # 屏幕自适应
  flutter_screenutil: ^5.9.3
  # 动画导航
  animated_bottom_navigation_bar: ^1.3.3
  # dialog
  flutter_smart_dialog: ^4.9.8+5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/default_spin.png

include: package:flutter_lints/flutter.yaml
analyzer:
  errors:
    always_declare_return_types: error  # 总是声明返回类型
    asset_field_not_list: error
    asset_not_string: error
    avoid_dynamic_calls: error
    avoid_print: error
    avoid_types_as_parameter_names: error
    avoid_void_async: error
    body_might_complete_normally_catch_error: error
    body_might_complete_normally_nullable: error
    case_expression_type_is_not_switch_expression_subtype: error
    cast_from_null_always_fails: error
    cast_from_nullable_always_fails: error
    collection_methods_unrelated_type: error
    constant_pattern_never_matches_value_type: error
    dead_code: error
    duplicate_export: error
    duplicate_hidden_name: error
    duplicate_ignore: error
    duplicate_import: error
    duplicate_shown_name: error
    empty_statements: error
    hash_and_equals: error
    implementation_imports: error
    invalid_dependency: error
    invalid_override_of_non_virtual_member: error   # 被@nonVirtual注解的方法子类不能重写
    invalid_use_of_visible_for_overriding_member: error
    invalid_use_of_visible_for_testing_member: error
    invalid_visibility_annotation: error
    invalid_visible_for_overriding_annotation: error
    literal_only_boolean_expressions: error
    missing_name: error
    missing_override_of_must_be_overridden: error
    missing_required_param: error  # 不能缺少必要的参数
    must_be_immutable: error
    must_call_super: error
    null_argument_to_non_null_type: error
    null_check_always_fails: error
    override_on_non_overriding_member: error
    path_does_not_exist: error
    path_not_posix: error
    path_pubspec_does_not_exist: error
    prefer_final_fields: error
    prefer_final_in_for_each: error
    prefer_final_locals: error
    prefer_function_declarations_over_variables: error
    prefer_relative_imports: error
    undefined_hidden_name: error
    undefined_referenced_parameter: error
    undefined_shown_name: error
    unnecessary_cast: error
    unnecessary_dev_dependency: error
    unnecessary_final: error
    unnecessary_import: error
    unnecessary_nan_comparison: error
    unnecessary_no_such_method: error
    unnecessary_non_null_assertion: error
    unnecessary_null_assert_pattern: error
    unnecessary_null_check_pattern: error
    unnecessary_null_comparison: error
    unnecessary_question_mark: error
    unnecessary_set_literal: error
    unnecessary_type_check: error
    unreachable_switch_case: error
    unused_field: error
    unused_import: error
    unused_label: error
    unused_local_variable: error
    unused_result: error
    unused_shown_name: error
    use_build_context_synchronously: error
    valid_regexps: error
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true
  exclude:
#        - test/**
#        - example/**
#        - sample/**
linter:
  rules:
    - always_declare_return_types
    - always_specify_types
    - avoid_bool_literals_in_conditional_expressions
    - avoid_dynamic_calls
    - avoid_field_initializers_in_const_classes
    - cancel_subscriptions
    - close_sinks
    - collection_methods_unrelated_type
    - combinators_ordering
    - deprecated_consistency
    - deprecated_member_use_from_same_package
    - directives_ordering
    - flutter_style_todos
    - join_return_with_assignment
    # - lines_longer_than_80_chars # 目前使用 150 行宽
    - literal_only_boolean_expressions
    - no_adjacent_strings_in_list
    - no_literal_bool_comparisons
    - no_self_assignments
    - no_wildcard_variable_uses
    - package_api_docs
    - parameter_assignments
    - prefer_asserts_in_initializer_lists
    - prefer_asserts_with_message
    - prefer_final_in_for_each
    - prefer_final_locals
    # - prefer_final_parameters # 需要讨论是否需要强制
    # - public_member_api_docs # 需要补的注释太多
    - prefer_null_aware_method_calls
    - prefer_relative_imports
    - prefer_single_quotes
    - prefer_void_to_null
    - sized_box_shrink_expand
    - sort_pub_dependencies
    - sort_unnamed_constructors_first
    - test_types_in_equals
    - throw_in_finally
    - tighten_type_of_initializing_formals
    - type_annotate_public_apis
    - unnecessary_await_in_return
    - unnecessary_breaks
    - unnecessary_null_aware_operator_on_extension_on_nullable
    - unnecessary_null_checks
    - unnecessary_parenthesis
    - unnecessary_raw_strings
    - unnecessary_statements
    - use_enums
    - use_if_null_to_convert_nulls_to_bools
    - use_is_even_rather_than_modulo
    - use_named_constants
    - use_raw_strings
    - use_test_throws_matchers
    - use_to_and_as_if_applicable

